#!/bin/bash

#append some declarations for functions present in IBNIZ, and silence warnings from them
#POSSIBLY: also append the ibniz_run function opening?

mkdir tempfiles 2>/dev/null

cat <<EOF >tempfiles/phase1_prefixed.c
#pragma clang diagnostic ignored "-Wincompatible-library-redeclaration"
int sqrt(int);
int sin(int);
int atan(int, int);
EOF

cat $1 >>tempfiles/phase1_prefixed.c

#Use clang to get some LLVM IR
clang -S -O3 -emit-llvm  tempfiles/phase1_prefixed.c -o tempfiles/phase2_llvm

#strip out only the ibniz_run function body. If we later support calling subroutines, we'll need to update this.
#awk '/ibniz_run/,/^}$/' tempfiles/phase2_llvm > tempfiles/phase3_body
cat tempfiles/phase2_llvm >tempfiles/phase3_body
#reduce allocation statments, alignments, types, commas, builtin functions, add spaces around parens, ensure new lines are separate tokens
sed -e 's/alloca/allocate/g' -e 's/align 4//g' -e 's/i32\*/at/g' -e 's/i32//g'  -re 's/call\s+@(sin|sqrt|atan)\(([^)]*)\)/\1 \2/g' <tempfiles/phase3_body >tempfiles/phase4_cleaned

#Run the now cleaned LLVM IR into our compiler.
cat tempfiles/phase4_cleaned  | ./compiler
